# Versione del file di configurazione
version: '3.8'

services:
  # Definizione del servizio per il bot TempRooms
  temprooms-bot:
    # Costruisce l'immagine usando il Dockerfile nella directory corrente (.)
    build: .
    # Nome del container per identificarlo facilmente
    container_name: temprooms-bot
    # Riavvia sempre il container in caso di errore per garantire l'uptime
    restart: always
    # Carica le variabili d'ambiente dal file .env che hai nella root del progetto
    env_file:
      - .env
    # Mappa la porta 3000 del container alla porta 3000 del tuo server host
    # Questo permette ai webhook di Stripe di raggiungere il tuo bot
    ports:
      - "3000:3000"
    # Gestione della persistenza del database SQLite
    volumes:
      # Mappa un volume Docker chiamato 'temprooms-db-data' alla cartella '/database'
      # all'interno del container. In questo modo il file del database sopravvive ai riavvii.
      - temprooms-db-data:/usr/src/app/database

# Definizione dei volumi Docker per la persistenza dei dati
volumes:
  temprooms-db-data:
